name: Continiuous Integration and Deployment
run-name: CI/CD
on: [push, pull_request]
jobs:
  Build_Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Nebula as a package
        run: |
          pip install -e .
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Format with black
        if: success() || failure() # make sure to run this step even if the previous one fails
        run: |
          pip install black
          black --check .
      - name: Test with pytest
        if: success() || failure() # make sure to run this step even if the previous one fails
        run: |
          pip install pytest
          pytest
  Build_Node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:p
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint with eslint
        run: |
          npm run lint
      - name: Test with Vitest
        if: success() || failure() # make sure to run this step even if the previous one fails
        run: |
          npm run test
      - name: Build with Vite
        if: success() || failure() # make sure to run this step even if the previous one fails
        run: |
          npm run build
      - name: Build Docs with Vitepress
        if: success() || failure() # make sure to run this step even if the previous one fails
        run: |
          npm run docs:build
