name: CI/CD
run-name: CI/CD
on: [push]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
                  cache: "pip"
            - name: Install python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install Nebula as a package
              run: |
                  pip install -e .
            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - name: Install Node dependencies
              run: |
                  npm ci
            - name: Lint with eslint
              run: |
                  npm run lint
            - name: Lint with flake8
              if: success() || failure() # make sure to run this step even if the previous one fails
              run: |
                  pip install flake8
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Format with black and isort
              if: success() || failure() # make sure to run this step even if the previous one fails
              run: |
                  pip install black
                  pip install isort
                  make check-format

    Test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: read
            checks: write
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
                  cache: "pip"
            - name: Install python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install Nebula as a package
              run: |
                  pip install -e .
            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - name: Install dependencies
              run: |
                  npm ci
                  npm run build-only
            - name: Test with Vitest
              if: success() || failure() # make sure to run this step even if the previous one fails
              run: |
                  npm run test -- --reporter=junit --outputFile=test-results/junit/vitest/test-results.xml
            - name: Test with pytest
              if: success() || failure() # make sure to run this step even if the previous one fails
              run: |
                  pip install pytest
                  pytest --junitxml=test-results/junit/pytest/test-results.xml
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action/composite@v2
              if: always()
              continue-on-error: true
              with:
                  junit_files: "test-results/junit/**/*.xml"
                  comment_mode: off

    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
                  cache: "pip"
            - name: Install python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - name: Install Node dependencies
              run: |
                  npm ci
            - name: Build Nebula as a package
              run: |
                  pip install -e .
            - name: Build with Vite
              run: |
                  npm run build
            - name: Build docs with Vitepress
              if: success() || failure() # make sure to run this step even if the previous one fails
              run: |
                  npm run docs:build
